package com.example.project_soa.model;
// Generated Mar 3, 2025, 11:14:06 AM by Hibernate Tools 6.5.1.Final

/**
 * Amulet generated by hbm2java
 */
public class Amulet implements java.io.Serializable {

	private Integer id;
	private int name;
	private Integer templeName;
	private int price;
	private String type;

	public Amulet() {
	}

	public Amulet(int name, int price) {
		this.name = name;
		this.price = price;
	}

	public Amulet(int name, Integer templeName, int price, String type) {
		this.name = name;
		this.templeName = templeName;
		this.price = price;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	public Integer getTempleName() {
		return this.templeName;
	}

	public void setTempleName(Integer templeName) {
		this.templeName = templeName;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
