package com.example.project_soa.model;
// Generated Mar 28, 2025, 10:00:24 PM by Hibernate Tools 6.5.1.Final

/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail implements java.io.Serializable {

	private Integer id;
	private int productId;
	private int orderId;

	public Orderdetail() {
	}

	public Orderdetail(int productId, int orderId) {
		this.productId = productId;
		this.orderId = orderId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

}
