package com.example.project_soa.model;
// Generated Mar 28, 2025, 10:00:24 PM by Hibernate Tools 6.5.1.Final

/**
 * Productorder generated by hbm2java
 */
public class Productorder implements java.io.Serializable {

	private Integer id;
	private String cusId;
	private int totalPrice;

	public Productorder() {
	}

	public Productorder(String cusId, int totalPrice) {
		this.cusId = cusId;
		this.totalPrice = totalPrice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

}
